comment: false
coverage:
  status:
    project:
      default:
        base: auto
        target: auto
        threshold: 0.05%
    patch:
      default:
        enabled: no
        if_not_found: success
