comment: off
coverage:
  status:
    project:
      default:
        base: auto
        target: auto
        threshold: null
    patch:
      default:
        base: auto
        target: 100%
        threshold: null
