/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

import * as jspb from './google-protobuf';
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsContext', null, global);
goog.exportSymbol('proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsEvent', null, global);
goog.exportSymbol('proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsEventMeta', null, global);
goog.exportSymbol('proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsRequest', null, global);
goog.exportSymbol('proto.java.com.google.subscribewithgoogle.client.ui.common.api.EventOriginator', null, global);
goog.exportSymbol('proto.java.com.google.subscribewithgoogle.client.ui.common.api.EventParams', null, global);
goog.exportSymbol('proto.java.com.google.subscribewithgoogle.client.ui.common.api.LinkRequest', null, global);
goog.exportSymbol('proto.java.com.google.subscribewithgoogle.client.ui.common.api.SkuSelected', null, global);
goog.exportSymbol('proto.java.com.google.subscribewithgoogle.client.ui.common.api.SmartBoxMessage', null, global);
goog.exportSymbol('proto.java.com.google.subscribewithgoogle.client.ui.common.api.SubscribeRequest', null, global);
goog.exportSymbol('proto.java.com.google.subscribewithgoogle.client.ui.common.api.ViewSubscriptionsRequest', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsContext = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsContext.repeatedFields_, null);
};
goog.inherits(proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsContext, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsContext.displayName = 'proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsContext';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsContext.repeatedFields_ = [9];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsContext.prototype.toObject = function(opt_includeInstance) {
  return proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsContext.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsContext} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsContext.toObject = function(includeInstance, msg) {
  var f, obj = {
    embedderOrigin: jspb.Message.getField(msg, 1),
    transactionId: jspb.Message.getField(msg, 2),
    referringOrigin: jspb.Message.getField(msg, 3),
    utmSource: jspb.Message.getField(msg, 4),
    utmCampaign: jspb.Message.getField(msg, 5),
    utmMedium: jspb.Message.getField(msg, 6),
    sku: jspb.Message.getField(msg, 7),
    readyToPay: jspb.Message.getField(msg, 8),
    labelList: jspb.Message.getRepeatedField(msg, 9)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsContext}
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsContext.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsContext;
  return proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsContext.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsContext} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsContext}
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsContext.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setEmbedderOrigin(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setTransactionId(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setReferringOrigin(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setUtmSource(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setUtmCampaign(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setUtmMedium(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setSku(value);
      break;
    case 8:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setReadyToPay(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.addLabel(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsContext.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsContext.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsContext} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsContext.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {string} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeString(
      2,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeString(
      3,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeString(
      4,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 5));
  if (f != null) {
    writer.writeString(
      5,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 6));
  if (f != null) {
    writer.writeString(
      6,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 7));
  if (f != null) {
    writer.writeString(
      7,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 8));
  if (f != null) {
    writer.writeBool(
      8,
      f
    );
  }
  f = message.getLabelList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      9,
      f
    );
  }
};


/**
 * optional string embedder_origin = 1;
 * @return {string}
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsContext.prototype.getEmbedderOrigin = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsContext.prototype.setEmbedderOrigin = function(value) {
  jspb.Message.setField(this, 1, value);
};


proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsContext.prototype.clearEmbedderOrigin = function() {
  jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsContext.prototype.hasEmbedderOrigin = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string transaction_id = 2;
 * @return {string}
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsContext.prototype.getTransactionId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsContext.prototype.setTransactionId = function(value) {
  jspb.Message.setField(this, 2, value);
};


proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsContext.prototype.clearTransactionId = function() {
  jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsContext.prototype.hasTransactionId = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional string referring_origin = 3;
 * @return {string}
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsContext.prototype.getReferringOrigin = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsContext.prototype.setReferringOrigin = function(value) {
  jspb.Message.setField(this, 3, value);
};


proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsContext.prototype.clearReferringOrigin = function() {
  jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsContext.prototype.hasReferringOrigin = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional string utm_source = 4;
 * @return {string}
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsContext.prototype.getUtmSource = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsContext.prototype.setUtmSource = function(value) {
  jspb.Message.setField(this, 4, value);
};


proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsContext.prototype.clearUtmSource = function() {
  jspb.Message.setField(this, 4, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsContext.prototype.hasUtmSource = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional string utm_campaign = 5;
 * @return {string}
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsContext.prototype.getUtmCampaign = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/** @param {string} value */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsContext.prototype.setUtmCampaign = function(value) {
  jspb.Message.setField(this, 5, value);
};


proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsContext.prototype.clearUtmCampaign = function() {
  jspb.Message.setField(this, 5, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsContext.prototype.hasUtmCampaign = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional string utm_medium = 6;
 * @return {string}
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsContext.prototype.getUtmMedium = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/** @param {string} value */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsContext.prototype.setUtmMedium = function(value) {
  jspb.Message.setField(this, 6, value);
};


proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsContext.prototype.clearUtmMedium = function() {
  jspb.Message.setField(this, 6, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsContext.prototype.hasUtmMedium = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional string sku = 7;
 * @return {string}
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsContext.prototype.getSku = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/** @param {string} value */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsContext.prototype.setSku = function(value) {
  jspb.Message.setField(this, 7, value);
};


proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsContext.prototype.clearSku = function() {
  jspb.Message.setField(this, 7, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsContext.prototype.hasSku = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional bool ready_to_pay = 8;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsContext.prototype.getReadyToPay = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 8, false));
};


/** @param {boolean} value */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsContext.prototype.setReadyToPay = function(value) {
  jspb.Message.setField(this, 8, value);
};


proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsContext.prototype.clearReadyToPay = function() {
  jspb.Message.setField(this, 8, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsContext.prototype.hasReadyToPay = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * repeated string label = 9;
 * @return {!Array<string>}
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsContext.prototype.getLabelList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 9));
};


/** @param {!Array<string>} value */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsContext.prototype.setLabelList = function(value) {
  jspb.Message.setField(this, 9, value || []);
};


/**
 * @param {!string} value
 * @param {number=} opt_index
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsContext.prototype.addLabel = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 9, value, opt_index);
};


proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsContext.prototype.clearLabelList = function() {
  this.setLabelList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsEventMeta = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsEventMeta, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsEventMeta.displayName = 'proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsEventMeta';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsEventMeta.prototype.toObject = function(opt_includeInstance) {
  return proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsEventMeta.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsEventMeta} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsEventMeta.toObject = function(includeInstance, msg) {
  var f, obj = {
    eventOriginator: jspb.Message.getField(msg, 1),
    isFromUserAction: jspb.Message.getField(msg, 2)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsEventMeta}
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsEventMeta.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsEventMeta;
  return proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsEventMeta.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsEventMeta} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsEventMeta}
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsEventMeta.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.java.com.google.subscribewithgoogle.client.ui.common.api.EventOriginator} */ (reader.readEnum());
      msg.setEventOriginator(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsFromUserAction(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsEventMeta.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsEventMeta.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsEventMeta} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsEventMeta.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {!proto.java.com.google.subscribewithgoogle.client.ui.common.api.EventOriginator} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeBool(
      2,
      f
    );
  }
};


/**
 * optional EventOriginator event_originator = 1;
 * @return {!proto.java.com.google.subscribewithgoogle.client.ui.common.api.EventOriginator}
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsEventMeta.prototype.getEventOriginator = function() {
  return /** @type {!proto.java.com.google.subscribewithgoogle.client.ui.common.api.EventOriginator} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {!proto.java.com.google.subscribewithgoogle.client.ui.common.api.EventOriginator} value */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsEventMeta.prototype.setEventOriginator = function(value) {
  jspb.Message.setField(this, 1, value);
};


proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsEventMeta.prototype.clearEventOriginator = function() {
  jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsEventMeta.prototype.hasEventOriginator = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional bool is_from_user_action = 2;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsEventMeta.prototype.getIsFromUserAction = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 2, false));
};


/** @param {boolean} value */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsEventMeta.prototype.setIsFromUserAction = function(value) {
  jspb.Message.setField(this, 2, value);
};


proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsEventMeta.prototype.clearIsFromUserAction = function() {
  jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsEventMeta.prototype.hasIsFromUserAction = function() {
  return jspb.Message.getField(this, 2) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.EventParams = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.java.com.google.subscribewithgoogle.client.ui.common.api.EventParams, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.java.com.google.subscribewithgoogle.client.ui.common.api.EventParams.displayName = 'proto.java.com.google.subscribewithgoogle.client.ui.common.api.EventParams';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.EventParams.prototype.toObject = function(opt_includeInstance) {
  return proto.java.com.google.subscribewithgoogle.client.ui.common.api.EventParams.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.java.com.google.subscribewithgoogle.client.ui.common.api.EventParams} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.EventParams.toObject = function(includeInstance, msg) {
  var f, obj = {
    smartboxMessage: jspb.Message.getField(msg, 1)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.java.com.google.subscribewithgoogle.client.ui.common.api.EventParams}
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.EventParams.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.java.com.google.subscribewithgoogle.client.ui.common.api.EventParams;
  return proto.java.com.google.subscribewithgoogle.client.ui.common.api.EventParams.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.java.com.google.subscribewithgoogle.client.ui.common.api.EventParams} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.java.com.google.subscribewithgoogle.client.ui.common.api.EventParams}
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.EventParams.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setSmartboxMessage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.EventParams.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.java.com.google.subscribewithgoogle.client.ui.common.api.EventParams.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.java.com.google.subscribewithgoogle.client.ui.common.api.EventParams} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.EventParams.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {string} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string smartbox_message = 1;
 * @return {string}
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.EventParams.prototype.getSmartboxMessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.EventParams.prototype.setSmartboxMessage = function(value) {
  jspb.Message.setField(this, 1, value);
};


proto.java.com.google.subscribewithgoogle.client.ui.common.api.EventParams.prototype.clearSmartboxMessage = function() {
  jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.EventParams.prototype.hasSmartboxMessage = function() {
  return jspb.Message.getField(this, 1) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsRequest.displayName = 'proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsRequest';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    context: (f = msg.getContext()) && proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsContext.toObject(includeInstance, f),
    event: jspb.Message.getField(msg, 2),
    meta: (f = msg.getMeta()) && proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsEventMeta.toObject(includeInstance, f),
    params: (f = msg.getParams()) && proto.java.com.google.subscribewithgoogle.client.ui.common.api.EventParams.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsRequest}
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsRequest;
  return proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsRequest}
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsContext;
      reader.readMessage(value,proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsContext.deserializeBinaryFromReader);
      msg.setContext(value);
      break;
    case 2:
      var value = /** @type {!proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsEvent} */ (reader.readEnum());
      msg.setEvent(value);
      break;
    case 3:
      var value = new proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsEventMeta;
      reader.readMessage(value,proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsEventMeta.deserializeBinaryFromReader);
      msg.setMeta(value);
      break;
    case 4:
      var value = new proto.java.com.google.subscribewithgoogle.client.ui.common.api.EventParams;
      reader.readMessage(value,proto.java.com.google.subscribewithgoogle.client.ui.common.api.EventParams.deserializeBinaryFromReader);
      msg.setParams(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getContext();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsContext.serializeBinaryToWriter
    );
  }
  f = /** @type {!proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsEvent} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getMeta();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsEventMeta.serializeBinaryToWriter
    );
  }
  f = message.getParams();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.java.com.google.subscribewithgoogle.client.ui.common.api.EventParams.serializeBinaryToWriter
    );
  }
};


/**
 * optional AnalyticsContext context = 1;
 * @return {?proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsContext}
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsRequest.prototype.getContext = function() {
  return /** @type{?proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsContext} */ (
    jspb.Message.getWrapperField(this, proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsContext, 1));
};


/** @param {?proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsContext|undefined} value */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsRequest.prototype.setContext = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsRequest.prototype.clearContext = function() {
  this.setContext(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsRequest.prototype.hasContext = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional AnalyticsEvent event = 2;
 * @return {!proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsEvent}
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsRequest.prototype.getEvent = function() {
  return /** @type {!proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsEvent} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {!proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsEvent} value */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsRequest.prototype.setEvent = function(value) {
  jspb.Message.setField(this, 2, value);
};


proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsRequest.prototype.clearEvent = function() {
  jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsRequest.prototype.hasEvent = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional AnalyticsEventMeta meta = 3;
 * @return {?proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsEventMeta}
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsRequest.prototype.getMeta = function() {
  return /** @type{?proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsEventMeta} */ (
    jspb.Message.getWrapperField(this, proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsEventMeta, 3));
};


/** @param {?proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsEventMeta|undefined} value */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsRequest.prototype.setMeta = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsRequest.prototype.clearMeta = function() {
  this.setMeta(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsRequest.prototype.hasMeta = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional EventParams params = 4;
 * @return {?proto.java.com.google.subscribewithgoogle.client.ui.common.api.EventParams}
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsRequest.prototype.getParams = function() {
  return /** @type{?proto.java.com.google.subscribewithgoogle.client.ui.common.api.EventParams} */ (
    jspb.Message.getWrapperField(this, proto.java.com.google.subscribewithgoogle.client.ui.common.api.EventParams, 4));
};


/** @param {?proto.java.com.google.subscribewithgoogle.client.ui.common.api.EventParams|undefined} value */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsRequest.prototype.setParams = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsRequest.prototype.clearParams = function() {
  this.setParams(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsRequest.prototype.hasParams = function() {
  return jspb.Message.getField(this, 4) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.SmartBoxMessage = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.java.com.google.subscribewithgoogle.client.ui.common.api.SmartBoxMessage, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.java.com.google.subscribewithgoogle.client.ui.common.api.SmartBoxMessage.displayName = 'proto.java.com.google.subscribewithgoogle.client.ui.common.api.SmartBoxMessage';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.SmartBoxMessage.prototype.toObject = function(opt_includeInstance) {
  return proto.java.com.google.subscribewithgoogle.client.ui.common.api.SmartBoxMessage.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.java.com.google.subscribewithgoogle.client.ui.common.api.SmartBoxMessage} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.SmartBoxMessage.toObject = function(includeInstance, msg) {
  var f, obj = {
    isClicked: jspb.Message.getField(msg, 1)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.java.com.google.subscribewithgoogle.client.ui.common.api.SmartBoxMessage}
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.SmartBoxMessage.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.java.com.google.subscribewithgoogle.client.ui.common.api.SmartBoxMessage;
  return proto.java.com.google.subscribewithgoogle.client.ui.common.api.SmartBoxMessage.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.java.com.google.subscribewithgoogle.client.ui.common.api.SmartBoxMessage} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.java.com.google.subscribewithgoogle.client.ui.common.api.SmartBoxMessage}
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.SmartBoxMessage.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsClicked(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.SmartBoxMessage.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.java.com.google.subscribewithgoogle.client.ui.common.api.SmartBoxMessage.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.java.com.google.subscribewithgoogle.client.ui.common.api.SmartBoxMessage} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.SmartBoxMessage.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {boolean} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeBool(
      1,
      f
    );
  }
};


/**
 * optional bool is_clicked = 1;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.SmartBoxMessage.prototype.getIsClicked = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 1, false));
};


/** @param {boolean} value */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.SmartBoxMessage.prototype.setIsClicked = function(value) {
  jspb.Message.setField(this, 1, value);
};


proto.java.com.google.subscribewithgoogle.client.ui.common.api.SmartBoxMessage.prototype.clearIsClicked = function() {
  jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.SmartBoxMessage.prototype.hasIsClicked = function() {
  return jspb.Message.getField(this, 1) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.LinkRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.java.com.google.subscribewithgoogle.client.ui.common.api.LinkRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.java.com.google.subscribewithgoogle.client.ui.common.api.LinkRequest.displayName = 'proto.java.com.google.subscribewithgoogle.client.ui.common.api.LinkRequest';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.LinkRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.java.com.google.subscribewithgoogle.client.ui.common.api.LinkRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.java.com.google.subscribewithgoogle.client.ui.common.api.LinkRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.LinkRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    subscriberOrMember: jspb.Message.getField(msg, 1),
    linkRequested: jspb.Message.getField(msg, 2)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.java.com.google.subscribewithgoogle.client.ui.common.api.LinkRequest}
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.LinkRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.java.com.google.subscribewithgoogle.client.ui.common.api.LinkRequest;
  return proto.java.com.google.subscribewithgoogle.client.ui.common.api.LinkRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.java.com.google.subscribewithgoogle.client.ui.common.api.LinkRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.java.com.google.subscribewithgoogle.client.ui.common.api.LinkRequest}
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.LinkRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setSubscriberOrMember(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setLinkRequested(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.LinkRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.java.com.google.subscribewithgoogle.client.ui.common.api.LinkRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.java.com.google.subscribewithgoogle.client.ui.common.api.LinkRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.LinkRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {boolean} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeBool(
      1,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeBool(
      2,
      f
    );
  }
};


/**
 * optional bool subscriber_or_member = 1;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.LinkRequest.prototype.getSubscriberOrMember = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 1, false));
};


/** @param {boolean} value */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.LinkRequest.prototype.setSubscriberOrMember = function(value) {
  jspb.Message.setField(this, 1, value);
};


proto.java.com.google.subscribewithgoogle.client.ui.common.api.LinkRequest.prototype.clearSubscriberOrMember = function() {
  jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.LinkRequest.prototype.hasSubscriberOrMember = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional bool link_requested = 2;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.LinkRequest.prototype.getLinkRequested = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 2, false));
};


/** @param {boolean} value */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.LinkRequest.prototype.setLinkRequested = function(value) {
  jspb.Message.setField(this, 2, value);
};


proto.java.com.google.subscribewithgoogle.client.ui.common.api.LinkRequest.prototype.clearLinkRequested = function() {
  jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.LinkRequest.prototype.hasLinkRequested = function() {
  return jspb.Message.getField(this, 2) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.SkuSelected = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.java.com.google.subscribewithgoogle.client.ui.common.api.SkuSelected, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.java.com.google.subscribewithgoogle.client.ui.common.api.SkuSelected.displayName = 'proto.java.com.google.subscribewithgoogle.client.ui.common.api.SkuSelected';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.SkuSelected.prototype.toObject = function(opt_includeInstance) {
  return proto.java.com.google.subscribewithgoogle.client.ui.common.api.SkuSelected.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.java.com.google.subscribewithgoogle.client.ui.common.api.SkuSelected} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.SkuSelected.toObject = function(includeInstance, msg) {
  var f, obj = {
    sku: jspb.Message.getField(msg, 1)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.java.com.google.subscribewithgoogle.client.ui.common.api.SkuSelected}
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.SkuSelected.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.java.com.google.subscribewithgoogle.client.ui.common.api.SkuSelected;
  return proto.java.com.google.subscribewithgoogle.client.ui.common.api.SkuSelected.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.java.com.google.subscribewithgoogle.client.ui.common.api.SkuSelected} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.java.com.google.subscribewithgoogle.client.ui.common.api.SkuSelected}
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.SkuSelected.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setSku(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.SkuSelected.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.java.com.google.subscribewithgoogle.client.ui.common.api.SkuSelected.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.java.com.google.subscribewithgoogle.client.ui.common.api.SkuSelected} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.SkuSelected.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {string} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string sku = 1;
 * @return {string}
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.SkuSelected.prototype.getSku = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.SkuSelected.prototype.setSku = function(value) {
  jspb.Message.setField(this, 1, value);
};


proto.java.com.google.subscribewithgoogle.client.ui.common.api.SkuSelected.prototype.clearSku = function() {
  jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.SkuSelected.prototype.hasSku = function() {
  return jspb.Message.getField(this, 1) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.SubscribeRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.java.com.google.subscribewithgoogle.client.ui.common.api.SubscribeRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.java.com.google.subscribewithgoogle.client.ui.common.api.SubscribeRequest.displayName = 'proto.java.com.google.subscribewithgoogle.client.ui.common.api.SubscribeRequest';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.SubscribeRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.java.com.google.subscribewithgoogle.client.ui.common.api.SubscribeRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.java.com.google.subscribewithgoogle.client.ui.common.api.SubscribeRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.SubscribeRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    subscribe: jspb.Message.getField(msg, 1)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.java.com.google.subscribewithgoogle.client.ui.common.api.SubscribeRequest}
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.SubscribeRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.java.com.google.subscribewithgoogle.client.ui.common.api.SubscribeRequest;
  return proto.java.com.google.subscribewithgoogle.client.ui.common.api.SubscribeRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.java.com.google.subscribewithgoogle.client.ui.common.api.SubscribeRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.java.com.google.subscribewithgoogle.client.ui.common.api.SubscribeRequest}
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.SubscribeRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setSubscribe(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.SubscribeRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.java.com.google.subscribewithgoogle.client.ui.common.api.SubscribeRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.java.com.google.subscribewithgoogle.client.ui.common.api.SubscribeRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.SubscribeRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {boolean} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeBool(
      1,
      f
    );
  }
};


/**
 * optional bool subscribe = 1;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.SubscribeRequest.prototype.getSubscribe = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 1, false));
};


/** @param {boolean} value */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.SubscribeRequest.prototype.setSubscribe = function(value) {
  jspb.Message.setField(this, 1, value);
};


proto.java.com.google.subscribewithgoogle.client.ui.common.api.SubscribeRequest.prototype.clearSubscribe = function() {
  jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.SubscribeRequest.prototype.hasSubscribe = function() {
  return jspb.Message.getField(this, 1) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.ViewSubscriptionsRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.java.com.google.subscribewithgoogle.client.ui.common.api.ViewSubscriptionsRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.java.com.google.subscribewithgoogle.client.ui.common.api.ViewSubscriptionsRequest.displayName = 'proto.java.com.google.subscribewithgoogle.client.ui.common.api.ViewSubscriptionsRequest';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.ViewSubscriptionsRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.java.com.google.subscribewithgoogle.client.ui.common.api.ViewSubscriptionsRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.java.com.google.subscribewithgoogle.client.ui.common.api.ViewSubscriptionsRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.ViewSubscriptionsRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    pb_native: jspb.Message.getField(msg, 1)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.java.com.google.subscribewithgoogle.client.ui.common.api.ViewSubscriptionsRequest}
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.ViewSubscriptionsRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.java.com.google.subscribewithgoogle.client.ui.common.api.ViewSubscriptionsRequest;
  return proto.java.com.google.subscribewithgoogle.client.ui.common.api.ViewSubscriptionsRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.java.com.google.subscribewithgoogle.client.ui.common.api.ViewSubscriptionsRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.java.com.google.subscribewithgoogle.client.ui.common.api.ViewSubscriptionsRequest}
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.ViewSubscriptionsRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setNative(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.ViewSubscriptionsRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.java.com.google.subscribewithgoogle.client.ui.common.api.ViewSubscriptionsRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.java.com.google.subscribewithgoogle.client.ui.common.api.ViewSubscriptionsRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.ViewSubscriptionsRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {boolean} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeBool(
      1,
      f
    );
  }
};


/**
 * optional bool native = 1;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.ViewSubscriptionsRequest.prototype.getNative = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 1, false));
};


/** @param {boolean} value */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.ViewSubscriptionsRequest.prototype.setNative = function(value) {
  jspb.Message.setField(this, 1, value);
};


proto.java.com.google.subscribewithgoogle.client.ui.common.api.ViewSubscriptionsRequest.prototype.clearNative = function() {
  jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.ViewSubscriptionsRequest.prototype.hasNative = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * @enum {number}
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.AnalyticsEvent = {
  UNKNOWN: 0,
  IMPRESSION_PAYWALL: 1,
  IMPRESSION_AD: 2,
  IMPRESSION_OFFERS: 3,
  IMPRESSION_SUBSCRIBE_BUTTON: 4,
  IMPRESSION_SMARTBOX: 5,
  IMPRESSION_SWG_BUTTON: 6,
  ACTION_SUBSCRIBE: 1000,
  ACTION_PAYMENT_COMPLETE: 1001,
  ACTION_ACCOUNT_CREATED: 1002,
  ACTION_ACCOUNT_ACKNOWLEDGED: 1003,
  ACTION_SUBSCRIPTIONS_LANDING_PAGE: 1004,
  ACTION_PAYMENT_FLOW_STARTED: 1005,
  ACTION_OFFER_SELECTED: 1006,
  ACTION_SWG_BUTTON_CLICK: 1007,
  EVENT_PAYMENT_FAILED: 2000,
  EVENT_CUSTOM: 3000,
  EVENT_SUBSCRIPTION_STATE: 4000
};

/**
 * @enum {number}
 */
proto.java.com.google.subscribewithgoogle.client.ui.common.api.EventOriginator = {
  UNKNOWN_CLIENT: 0,
  SWG_CLIENT: 1,
  AMP_CLIENT: 2,
  PROPENSITY_CLIENT: 3,
  SWG_SERVER: 4,
  PUBLISHER_CLIENT: 5
};

goog.object.extend(exports, proto.java.com.google.subscribewithgoogle.client.ui.common.api);
